apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing-service
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:14-alpine
        envFrom:
        - secretRef:
            name: db-credentials
        command: ['sh', '-c',
          "until pg_isready -h $(DB_HOST) -U $(POSTGRES_USER); do echo waiting for database; sleep 2; done;"]
      - name: init-schema
        image: localhost:5000/listing-service:latest
        envFrom:
        - secretRef:
            name: db-credentials
        command: ['node', 'scripts/init-schema.js']
      containers:
      - name: listing-service
        image: localhost:5000/listing-service:latest
        ports: # the container port should be 6000 to match the service port
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB