apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:14-alpine
        envFrom:
        - secretRef:
            name: db-credentials
        command: ['sh', '-c',
          "until pg_isready -h $(DB_HOST) -U $(POSTGRES_USER); do echo waiting for database; sleep 2; done;"]
      containers:
      - name: analytics-service
        image: localhost:5000/analytics-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB