apiVersion: v1
kind: Service
metadata:
  name: metabase-service
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_HOST
          value: "postgres-service"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_DBNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: MB_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: MB_SITE_URL
          value: "http://16.171.140.122/metabase"
        volumeMounts:
        - name: metabase-storage
          mountPath: /metabase-data
      volumes:
      - name: metabase-storage
        persistentVolumeClaim:
          claimName: metabase-pvc