# Metabase + Ingress Configuration
# Apply into namespace: plot-listing
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: plot-listing
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "listingdb"
  MB_DB_HOST: "db-cluster"
  MB_DB_PORT: "5432"
  MB_DB_USER: "user"
  MB_DB_PASS: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: plot-listing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_TYPE
            - name: MB_DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_DBNAME
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_HOST
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PASS
            - name: JAVA_TIMEZONE
              value: "UTC"
            - name: MB_SITE_URL
              value: "http://16.171.140.122/metabase"
            - name: MB_FORWARD_PROXY_CHECK_HEADERS
              value: "true"
            - name: MB_FORCE_HTTPS
              value: "false"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 300
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: plot-listing
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: metabase
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
  namespace: plot-listing
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /metabase
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
