# Metabase — fixed (strip /metabase prefix with Traefik middleware)
# Apply into namespace: plot-listing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: plot-listing
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "listingdb"
  MB_DB_HOST: "db-cluster"
  MB_DB_PORT: "5432"
  MB_DB_USER: "user"
  MB_DB_PASS: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: plot-listing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_TYPE
            - name: MB_DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_DBNAME
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_HOST
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PASS
            # optional timezone and site url (only used for links)
            - name: JAVA_TIMEZONE
              value: "UTC"
            - name: MB_SITE_URL
              value: "http://16.171.140.122/metabase"
            - name: MB_FORWARD_PROXY_CHECK_HEADERS
              value: "true"
            - name: MB_FORCE_HTTPS
              value: "false"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 300
            periodSeconds: 60
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: plot-listing
spec:
  type: ClusterIP
  selector:
    app: metabase
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
# Traefik Middleware (strip the /metabase prefix before proxying to metabase)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-metabase
  namespace: plot-listing
spec:
  stripPrefix:
    prefixes:
      - /metabase
      - /metabase/
    forceSlash: false
---
# Ingress for Metabase that attaches the strip middleware and has higher priority
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
  namespace: plot-listing
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # attach middleware (use <namespace>-<name>@kubernetescrd)
    traefik.ingress.kubernetes.io/router.middlewares: plot-listing-strip-metabase@kubernetescrd
    # give this route higher priority so it matches before a generic frontend ingress
    traefik.ingress.kubernetes.io/router.priority: "20"
    # optionally set entrypoints if you use HTTPS (websecure) or plain (web)
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /metabase
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
          - path: /metabase/
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
  # Uncomment and configure TLS if you have a cert/secret:
  # tls:
  #   - hosts:
  #       - metabase.example.com
  #     secretName: metabase-tls
